= JPdfBookmarks v3.0.0 Maven
life888888
:doctype: article
:encoding: utf-8
:lang: zh
:toc: left
:numbered:
:experimental:

JPdfBookmarks v3.0.0 Maven is mirgrate from jpdfbookmarks-code-r213-branches-pdfbox.tar.gz (https://sourceforge.net/projects/jpdfbookmarks/)

jpdfbookmarks code-r213 branches pdfbox

== Build System requirement

* JDK 9.x (JDK 9+)
* Maven 3.6.x+

== How to build and package ?

=== Download Source

* Download `Releases/v3.0.0-maven` (jpdfbookmarks-3.0.0-maven)

* Unzip JPdfBookmarks-3.0.0-maven.tar.gz or JPdfBookmarks-3.0.0-maven.zip

=== Build and Package

[source,bash]
----
cd JPdfBookmarks-3.0.0-maven
mvn clean package

cd jpdfbookmarks_core/target
----

your can find:

* Binary Release
** jpdfbookmarks-3.0.0.tar.gz
** jpdfbookmarks-0.0.0.zip

* Source Release
** jpdfbookmarks-src-3.0.0.tar.gz
** jpdfbookmarks-src-0.0.0.zip

== HOW TO INSTALL AND UNINSTALL

Same as README Section `HOW TO INSTALL AND UNINSTALL`

== HOW TO EXECUTE

Same as README Section `HOW TO EXECUTE`

== Why Change to Maven Build Tools?

* Package
** No more need for `Packaging` directory 
** No more need for `Packaging/jpdfbookmarks_cli.exe` in source
** No more need for `Packaging/jpdfbookmarks.exe` in source
** No need to install launch4j anymore 
** No need to install launch4j 7zip
** Windows and Linux developers use the same configuration files to build and package projects.
* It is no longer necessary to include the following jar files in the `jpdfbookmarks_lib/` directory
* Developers can use different IDE tools (NetBeans , Eclipse , IntelliJ IDEA) to open or import this Maven project.

== Guaranteed

The retained code and properties files are guaranteed to be consistent with jpdfbookmarks-code-r213-branches-pdfbox.tar.gz and have not been modified.

== Changes

The change content of the entire project converted from 3.0.0(branches pdfbox) to 3.0.0-maven version can refer to https://github.com/life888888/JPdfBookmarks-Maven-Patch
